# Generated by Django 5.2.1 on 2025-06-05 03:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_assignmentsubmission_is_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmissioncomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentsubmissioncomment',
            name='end_offset',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmissioncomment',
            name='start_offset',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmissioncomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
