# Generated by Django 5.2.1 on 2025-06-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assignmentsubmissioncomment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmissioncomment',
            name='comment_type',
            field=models.CharField(choices=[('linter', 'Linter'), ('file', 'File'), ('general', 'General')], default='general', max_length=10),
        ),
    ]
